### PR TITLE
Additions to make work well with Cetrus Abstraction library

### PR DESCRIPTION
**Pull request by torlangballe**
Hi. Sorry it's such a big change all at once, I just really wanted to see if the project was feasable. It was!

### CODE REVIEW

**Review by angelolloqui — COMMENTED** [review]
Thanks for the PR! I will take a closer look to it as soon as I have some time. It looks great!

**Comment by angelolloqui** [comment]
Very quickly, what I am missing is some extra tests covering the new functionality. As commented, I will review the code ASAP

**Comment by torlangballe** [comment]
Hi

I don’t have any unit tests or anything, but have been making them work on specific files.

A good start could be the files in Cetrus that can be directly translated to kotlin:

ZAlignment.swift
ZButton.swift
ZColor.swift
ZDebug.swift
ZMath.swift
ZPos.swift
ZRect.swift
ZShapeView.swift
ZSize.swift
ZTime.swift
ZTitleBar.swift
ZUrlCache.swift
ZWords.swift

(I just realized I haven’t renamed the swift files, want the names to contain IOS or Apple if they are NOT translatable)

These should pretty much translate 100%

tor

**Comment by torlangballe** [comment]
Hi Angel

How did it go looking at my changes? Anything else I can help with?

Regards,

Tor

**Comment by angelolloqui** [comment]
Hi, I am in the middle of a relocation so all my free time goes there. I hope to be able to review it before end of year. Does this block you in any way?

**Comment by torlangballe** [comment]
Hi

No, not at all, I’ll be away for two weeks then Christmas now too, just wanted to make sure you had everything you needed :-)
Good luck with the relocaiton,

Cheers from Tor

**Comment by angelolloqui** [comment]
Hi @torlangballe, I have merged your branch into /feature/cetrus to be able to work on it before merging. However, there are a few important issues. Please check #84 for details

**Comment by torlangballe** [comment]
Hi

I made a new branch and did 

swift package update

But get errors:

error: Build input files cannot be found: '/Users/tor/swift/github.com/angelolloqui/SwiftKotlin/.build/checkouts/bocho--9124166418598778832/Sources/Bocho/DotYanagiba/DotYanagibaReader.swift'

So I did

swift package generate-xcodeproj

Then I can build the framework from the workspace.

However,  the command line and app project are red in the project navigator and I cannot choose them.

Is there anything you recon I'm doing wrong? Maybe good for other users too :-) 

tor

**Comment by torlangballe** [comment]
Hi Angel

Not sure how to message you about general stuff here, but I made my first change and pushed to cetrus branch with a swift and kotlin test file too. Does that look like I'm on the right track?

**Pull request merged**
