### PR TITLE
Update AppIcon

### PR DESCRIPTION
**Pull request by toshi0383**
https://github.com/angelolloqui/SwiftKotlin/issues/124

スクリーンショット 2020-12-08 17 20 31

### CODE REVIEW

**Review by angelolloqui — APPROVED** [review]
Thanks!

**Comment by GeylanKalafMohe** [comment]
@toshi0383 @angelolloqui How to run the project as there's no release build yet? There's an error while building manually:
Bildschirmfoto 2020-12-08 um 19 07 36

**Comment by angelolloqui** [comment]
Please follow the instructions on the readme and try again. The error should go away

**Comment by GeylanKalafMohe** [comment]
Thank you it worked!

**Pull request merged**
