### PR TITLE
Updated swift-transform to v0.1.3

### PR DESCRIPTION
**Pull request by thmatuza**
I encountered the issue https://github.com/angelolloqui/SwiftKotlin/issues/72.

It may be due to some version issue in swift-transform, so I updated it to the latest version v0.1.3.

I can successfully build this after updating it.

I also fixed some Swift 4 related warnings.

### CODE REVIEW

**Comment by thmatuza** [comment]
Sorry, I misunderstood. https://github.com/angelolloqui/SwiftKotlin/issues/72 is happen only when target is SwiftKotlin-Package.
I can successfully build this without updating swift-transform for SwiftKotlinApp target.

**Comment by thmatuza** [comment]
OK. I figured out what is probably causing the link error.
https://github.com/vapor/vapor/issues/1624
Some files on AST are using String but not importing Foundation.
I added dummy files to import Foundation for workaround.

**Comment by angelolloqui** [comment]
Sorry for the delay. I am not merging this yet because I have been working on changing the project layout to use a workspace with 3 projects (to resolve the issue of SPM not supporting Mac apps). Together with that, I am updating to Xcode 10, but there is an issue in the Swift-transform dependency, so it is taking me a little longer than expected. 

I hope to find the time soon to integrate all together, including your fixes.

Thanks for the PR!

**Comment by angelolloqui** [comment]
For reference, this fixes the issue with Xcode10 https://github.com/yanagiba/swift-ast/pull/89

**Comment by angelolloqui** [comment]
Check the new https://github.com/angelolloqui/SwiftKotlin/pull/80

**Pull request closed without merging**
